# Generated by Django 4.2 on 2024-08-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
